# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=40)),
                ('value', models.IntegerField()),
                ('health', models.IntegerField()),
                ('role', models.CharField(max_length=16)),
            ],
        ),
    ]
